.package: &package
  image: ${docker_registry}utils/docker:latest-rpm
  stage: build
  tags:
    - cf
    - docker
  script:
    - printf "FROM ${docker_registry}rpmbuild:$dist-$arch-onbuild" > Dockerfile
    - if [ -z "$CI_COMMIT_TAG" ]; then
        rpm_release="0.$CI_PIPELINE_ID";
      else
        rpm_release=`rpm --query --queryformat "%{release}\n" --specfile ${namespace}$CI_PROJECT_NAME.spec | head -n 1 | awk -F"." "{print $1}"`;
      fi
    - name=$(echo $CI_PROJECT_NAME| tr '[:upper:]' '[:lower:]')
    - docker login ${docker_registry} -u ${docker_user} -p ${docker_password}
    - docker image build --pull
                             -t $name:latest-$dist-$arch
                             --build-arg "project=omniEvents"
                             --build-arg "rpm_release=$rpm_release"
                             --build-arg "spec_file=omniEvents.spec"
                             --build-arg "arch=$arch" .
    - id=$(docker container create $name:latest-$dist-$arch)
    - docker container cp $id:/root/rpmbuild/RPMS/ output/
    - docker container rm -f $id
    - docker image rm -f $name:latest-$dist-$arch
  artifacts:
    paths:
      - output/*/*.rpm
    expire_in: 2 days

package:el6:
  variables:
    dist: el6
    arch: x86_64
  <<: *package

package:el6-i386:
  variables:
    dist: el6
    arch: i686
  <<: *package

package:el7:
  variables:
    dist: el7
    arch: x86_64
  <<: *package

deploy:
  image: ${docker_registry}centos:7
  stage: deploy
  dependencies: []
  script:
    - if [ -n "$jenkins_url" ]; then
        curl --insecure -X POST $jenkins_url/job/$CI_PROJECT_NAMESPACE/job/omniEvents-$CI_COMMIT_REF_NAME/buildWithParameters?pipeline_id=$CI_PIPELINE_ID --user $jenkins_user:$jenkins_api_token;
      fi

.s3: &s3
  image: ${docker_registry}utils/s3cmd:el6-createrepo
  stage: deploy
  tags:
    - s3
  script:
    - /usr/bin/s3cmd sync s3://$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yum/$CI_COMMIT_REF_SLUG/$dist/$arch .
    - mkdir -p $arch
    - for file in `find output -name *.rpm`; do
        cp $file $arch;
      done
    - repomanage --keep=2 --old $arch| xargs rm -f; createrepo --update $arch
    - /usr/bin/s3cmd sync -F -v --delete-removed $arch s3://$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yum/$CI_COMMIT_REF_SLUG/$dist/  && s3cmd setacl -v s3://$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/yum/$CI_COMMIT_REF_SLUG/$dist --acl-public --recursive || true

deploy-el7:
  variables:
    dist: el7
    arch: x86_64
  dependencies:
    - package:el7
  <<: *s3

deploy-el6:
  variables:
    dist: el6
    arch: x86_64
  dependencies:
    - package:el6
  <<: *s3

deploy-el6-i386:
  variables:
    dist: el6
    arch: i686
  dependencies:
    - package:el6-i386
  <<: *s3
