#!/bin/sh

set -e

# Those using dependency based boot sequencing with sysv-rc and
# installing omniorb-eventservice using version 1:2.6.2-1 and earlier
# would have the wrong runlevel symlinks.  Recover from this.
if [ "$1" = "configure" ] && dpkg --compare-versions "$2" le "1:2.6.2-1" \
    && [ -f /etc/rc3.d/S[0-9][0-9]omniorb-eventservice ] && [ ! -f /etc/rc2.d/S[0-9][0-9]omniorb-eventservice ]
then
    update-rc.d -f omniorb-eventservice remove
fi

#DEBHELPER#
